config/routes.rb
class CategoryConstraints
  def self.matches? request
    !Category.find_by_alias(request.path_parameters[:category]).nil?
  end
end

class PageLinkConstraints
  def self.matches? request
    !Page.find_by_link(request.path_parameters[:link]).nil?
  end
end

class CompanySubdomainConstraints
  def self.matches? request
    !!(m = request.server_name.match(/^([\w\d\-]+)\.naobzore/) and (Site.find_by_subdomen(m[1]).try(:company) || Subdomain.find_by_name(m[1]).try(:company)))
  end
end

OnshowLoc::Application.routes.draw do
  def likes
    post :like
    post :ignore
    post :favorite
  end

  scope :module => "minisite" do
    constraints CompanySubdomainConstraints do
      root :to => 'home#index'
      resources :goods, :only => [:index, :show] do
        member do
          likes
        end
      end
      resources :services, :only => [:index, :show] do
        member do
          likes
        end
      end
      resources :users, :only => [] do
        member do
          put :subscribe
        end
      end
      resources :news, :only => [] do
        resources :comments, :only => [:index, :create]
        member do
          likes
        end
      end
      get '/news' => 'news#index'
      get '/news/:id' => 'news#show'
      resources :campaigns, :only => [:index, :show] do
        member do
          post :campaign_send
          likes
        end
        resources :comments, :only => [:index, :create]
      end
      get '/about' => 'home#about', :as => :about
      get '/contacts' => 'home#contacts', :as => :contacts
      get '/search' => 'home#search', :as => :search
      resources :jobs, :only => [:index, :show] do
        resources :comments, :only => [:index, :create]
        member do
          likes
        end
      end
      resources :resumes, :only => [] do
        member do
          post :resume_send
        end
      end
      resources :feedbacks, :only => [] do
        member do
          likes
        end
      end
      resources :messages, :only => :create
    end
  end # minisite

  mount Ckeditor::Engine => '/ckeditor'

  match "favorite/:type/:id/:status" => "favorites#plus"
  get "like/:type/:id" => "likes#add"
  
  get "/cabinet/ajax/:id/:type" => "cabinet#ajax"
  get "/cabinet/switching/:id/:type/:direction/:type_one" => "cabinet#switching"
  get "cabinet/:type" => "cabinet#entities"

  get "/goods/ajax/:id/:type" => "goods#ajax"
  get "/goods/switching/:id/:direction/" => "goods#switching"
  get "/goods/switching/:category/:id/:direction/" => "goods#switching"
  
  get "/services/ajax/:id/:type" => "services#ajax"
  get "/services/switching/:id/:direction/" => "services#switching"
  get "/services/switching/:category/:id/:direction/" => "services#switching"
  
  get "/jobs/ajax/:id/:type" => "jobs#ajax"
  get "/jobs/switching/:id/:direction/" => "jobs#switching"
  get "/jobs/switching/:category/:id/:direction/" => "jobs#switching"
  
  get "/companies/ajax/:id/:type" => "companies#ajax"
  get "/companies/switching/:id/:direction/" => "companies#switching"
  get "/companies/switching/:category/:id/:direction/" => "companies#switching"
  
  get "/campaigns/ajax/:id/:type" => "campaigns#ajax"
  get "/campaigns/switching/:id/:direction/" => "campaigns#switching"
  get "/campaigns/switching/:category/:id/:direction/" => "campaigns#switching"

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  ActiveAdmin.routes(self)
  
  default_url_options :host => "naobzore.ru"

  resources :cabinet

  resources :products

  resources :pages

  resources :banners

  resources :sites
  
  get "help" => "help#index"
  get "help/:category" => "help#index"
  get "help/:alias" => "help#index"
  get "help/show/:alias" => "help#show"
  
  get "/feedbacks" => "feedbacks#index"
  get "/feedbacks/:category" => "feedbacks#index"
  post "/feedbacks/add" => "feedbacks#add"
  
  get "campaigns/" => "campaigns#index"
  get "campaigns/:category" => "campaigns#index", :constraints => CategoryConstraints
  get "campaigns/:id" => "campaigns#show", :as => :campaign
  get "campaigns/:category/:id" => "campaigns#show"
  
  get "news/" => "news#index"
  get "news/:category" => "news#index", :constraints => CategoryConstraints
  get "news/:id" => "news#show", :as => 'show_news'
  get "news/:category/:id" => "news#show"

  get "/companies" => "companies#index"
  get "/companies/:category" => "companies#index"

  get "/jobs" => "jobs#index"
  get "/jobs/:category" => "jobs#index", :constraints => CategoryConstraints
  get "/jobs/:id" => "jobs#show", :as => :job
  get "/jobs/:category/:id" => "jobs#show"
  
  get "/resume" => "resume#index"
  get "/resume/:category" => "resume#index", :constraints => CategoryConstraints
  get "/resume/:id" => "resume#show"
  get "/resume/:category/:id" => "resume#show"

  get "/services" => "services#index"
  get "/services/:category" => "services#index", :constraints => CategoryConstraints
  get "/services/:id" => "services#show", :as => :service
  get "/services/:category/:id" => "services#show"

  get "/goods" => "goods#index"
  get "/goods/:category" => "goods#index", :constraints => CategoryConstraints
  get "/goods/:id" => "goods#show", :as => :good
  get "/goods/:category/:id" => "goods#show"

  resources :categories

  match '/social/export' => 'social#export', :as => :social_export

  namespace :company_panel do
    root :to => 'home#index'

    post '/widgets/save_order' => 'home#save_widgets_order'
    get '/mail' => 'home#mail'
    get '/site_control' => 'home#site_control'
	
	get '/messages/dialog' => 'messages#dialog'

    resources :statistics, :only => [:index]
    resources :news, :only => [:new, :create]
    resources :users, :only => [:edit, :update, :destroy] do
      member do
        get :edit_password
        put :update_password
        get :edit_email
        put :update_email
        get :delete_account
      end
      collection do
        get :search
      end
    end
		resources :messages, :only => [:index, :create]
		resources :resumes, :only => [:index, :show, :destroy] do
			member do
				post :offer
			end
      collection do
        get :search
      end
		end
    resources :subscribes, :only => [:index, :destroy]
    resources :emails, :only => [:index]
    resources :sms, :only => [:index]
    resources :calls, :only => [:index]
    %w(goods services campaigns jobs).each do |r|
      resources r.to_sym, :only => [:index, :new, :create, :edit, :update] do
        collection do
          post :mass_publish
          post :mass_unpublish
          post :mass_destroy
          get :search
        end
        member do
          post :mass_set_photos
          get :load_image
        end
      end
    end
    get '/campaigns/entities' => 'campaigns#entities', :as => 'campaigns_entities'
    resources :price_lists, :only => [:new, :create]
    resources :price_entities, :only => [:index, :update] do
      collection do
        post :mass_destroy
        post :export
      end
      member do
        post :mass_set_photos
        get :load_image
      end
    end
    get '/pages/:link' => 'pages#show', :constraints => PageLinkConstraints, :as => :page
    resources :categories, :only => [:index]
    resources :photos, :only => [:index, :create, :update, :destroy] do
      collection do
        post :mass_destroy
        get :entities
      end
    end
    resources :packages, :only => [] do
      collection do
        get :placing
        get :communication
      end
    end
    resources :companies_packages, :only => [:create] do
      member do
        post :set_auto
      end
    end
    resources :banners, :only => [:new, :create]
    resources :companies, :only => [:edit, :update] do
      member do
        get :legal
        get :logotype
        get :tmp_logotype
        get :schedule
        get :crediting
      end
    end
    resources :banks
    resources :companies_users, :only => [:index, :create, :destroy] do
      collection do
        get :search
        get :user_by_email
        put :user_phone_email
        post :invite
      end
    end
    resources :deliveties, :warranties
    resources :menus, :only => [:index] do
      collection do
        post :set_order
      end
    end
    resources :subdomains, :only => [:index] do
      collection do
        post :mass_save
      end
    end
    resources :sites, :only => [:update] do
      member do
        get :stats
        get :webmaster
        get :sitemap
        get :robots
        get :construct
        put :commit
      end
    end
    resources :invoices do
      member do
        put :pay
      end
      collection do
        get :movement
      end
    end
    resources :factures
    resources :acts
    resources :tutorials, :only => [:index]
    resources :feedbacks, :only => [:index]
    resources :companies_resumes, :only => [:index, :destroy] do
      member do
        post :change_status
      end
      collection do
        post :mass_reject
        delete :mass_destroy
      end
    end
    resources :notifications, :only => [:index]
    resources :folders
  end

  root :to => 'home#index'

end

app/controllers/campaigns_controller.rb
# coding: utf-8

class CampaignsController < ApplicationController
  after_filter :save_statistics, :only => [:show]

  #--------------------------------------------------------------------------------
  # Список акций
  #--------------------------------------------------------------------------------
  def index
  
    query = {
      :count => (params[:count]) ? params[:count] : '10',
      :sort  => (params[:sort]) ? params[:sort] : 'created_at',
      :order => (params[:order]) ? params[:order] : 'DESC'
    }
    where = {
      :category   => Category.get_child_id_by_alias(params[:category])
    }


    #Основные запросы
    @campaigns = Campaign.where(where[:category])
                         .paginate(:page => params[:page], :per_page => query[:count])
                         .order(query[:sort] + ' ' + query[:order])

    #Второстепенные запросы
    @category = params[:category] != nil ? Category.find_by_alias(params[:category]) : nil
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @campaigns }
    end
  end

  #------------------------------------------------------------------------------------
  # Обзор акции
  #------------------------------------------------------------------------------------
  def show
    @campaign = Campaign.find(params[:id])
    @feedbacks = Feedback.where('entity_type = "Campaign" AND entity_id = ?', @campaign.id).limit(Feedback.get_limit()).order('id DESC')
    @category = params[:category] != nil ? Category.find_by_alias(params[:category]) : nil
    
    @other_campaign = Campaign.where('category_id = ?', @campaign.category_id).limit(6).order('id ASC')
    render :template => 'campaigns/show', :layout => 'layouts/simple_ext_show'
  end

  #------------------------------------------------------------------------------------  
  # Получение данных для POPUP
  #------------------------------------------------------------------------------------
  def ajax
    
    @campaign = Campaign.find(params[:id])
    @feedbacks = Feedback.where('entity_type = "Campaign" AND entity_id = ?', @campaign.id).limit(Feedback.get_limit()).order('id DESC')

    @result = []
    @result[0] = @campaign.company
    @result[1] = render_to_string("layouts/popup/campaign_header", :layout => false)
    @result[2] = render_to_string("layouts/popup/campaign_content", :layout => false)
    @result[3] = user_signed_in? ? render_to_string("layouts/popup/campaign_feedback", :layout => false) : ''
    
    if Visit.plus(params[:id], 'campaign', request.remote_ip)
      @campaign.views = (@campaign.views == nil) ? @campaign.views = 1 : @campaign.views + 1
      @campaign.save
    end
    
    response.headers['Content-type'] = "text/plain; charset=utf-8"
    render :text => @result.to_json
  end
  
  #-------------------------------------------------------------------------------------
  # Переключение в попапе следующее/предыдущее
  #-------------------------------------------------------------------------------------
  def switching
    
    query = {
      :count => (params[:count]) ? params[:count] : '10',
      :sort  => (params[:sort]) ? params[:sort] : 'created_at',
      :order => (params[:order]) ? params[:order] : 'DESC'
    }
    where = {
      :category => ''
    }
    
    # Проверяем есть ли дочерние категории
    if params[:category]
      temp = Category.get_child_id_by_alias(params[:category])
      if temp != ''
        where[:category] = temp
      else
        where[:category] = 'category_id = ' + params[:category]
      end
    end
    
    # Получение всех айдишников с учетом сортировки и фильтров
    campaigns_id = Campaign.select('id')
                           .where(where[:category])
                           .order(query[:sort] + ' ' + query[:order])
                
    query_id = nil
    
    # Получение id запрашиваемой сущьности
    i = 0
    campaigns_id.each do |campaign_id|
      if campaign_id.id.to_i == params[:id].to_i
        if params[:direction] == 'next'
          i += 1
        elsif params[:direction] == 'prev'
          i -= 1
        end
        break
      end
      i += 1
    end #теперь у нас есть id
    
    # В случии отсутствия следующей или предыдущей сущности
    # в результат выдаем либо первую либо последнюю сущьность в щависимости от направления
    if campaigns_id[campaigns_id.count - 1].id.to_i == params[:id].to_i && params[:direction] == 'next'
      query_id = campaigns_id[0].id
    elsif campaigns_id[0].id.to_i == params[:id].to_i && params[:direction] == 'prev'
      query_id = campaigns_id[campaigns_id.count - 1].id
    else
      query_id = campaigns_id[i].id
    end
    
    @campaign = Campaign.find(query_id)
    @feedbacks = Feedback.where('entity_type = "Campaign" AND entity_id = ?', @campaign.id).limit(Feedback.get_limit()).order('id DESC')
    
    if @campaign

      @result = []
      @result[0] = @campaign.company
      @result[1] = render_to_string("layouts/popup/campaign_header", :layout => false)
      @result[2] = render_to_string("layouts/popup/campaign_content", :layout => false)
      @result[3] = user_signed_in? ? render_to_string("layouts/popup/campaign_feedback", :layout => false) : ''
      @result[10] = @campaign
      
      if Visit.plus(@campaign.id, 'campaign', request.remote_ip)
        @campaign.views = (@campaign.views == nil) ? @campaign.views = 1 : @campaign.views + 1
        @campaign.save
      end
    else
      @result = 0
    end
    
    response.headers['Content-type'] = "text/plain; charset=utf-8"
    render :text => @result.to_json
  end
 
	private

  def save_statistics
    Statistic.create(:entity_id => @campaign.id, :entity_type => 'Campaign', :user_id => current_user.try(:id), :ip => request.remote_ip)
  end
end

app/controllers/company_panel/campaigns_controller.rb
# encoding: utf-8

class CompanyPanel::CampaignsController < CompanyPanel::EntitiesController
  def initialize
    super
    @entity_type = 'Campaign'
  end

  def create
    super
  end

  def update
    %w(start_at end_at).each do |field|
      params[:entity][field] = DateTime.parse(params[:entity][field]) if params[:entity][field]
    end
    super
  end

  def new
    @entity = @entity_type.constantize.new(:company_id => @company.id, :end_at => Time.now + 1.month)
    @service = Good.limit(10)
    @service += Service.limit(10)
    @h1 = 'Добавление акции/скидки'
  end

  def edit
    super
    @h1 = 'Редактирование акции/скидки'
  end

  def entities
    entity_types = %w(Good Service)
    @entities = entity_types.map { |entity_type| entity_type.constantize.where(:article => params[:q]) }.flatten
    @entities = entity_types.map { |entity_type| entity_type.constantize.where('name LIKE ?', "%#{params[:q]}%").limit(10) }.flatten if @entities.empty?
    render :json => @entities.map { |entity| entity.as_json.merge({ :entity_type => entity.class.to_s })}
  end
end

app/controllers/minisite/base_controller.rb
# encoding: utf-8

class Minisite::BaseController < ApplicationController
  before_filter :find_company_by_subdomain
  before_filter lambda { @site = @company.site }
  before_filter lambda { @construct_mode = !!params[:construct_mode] }

  layout 'minisite'

  def find_company_by_subdomain
    m = request.server_name.match(/^([\w\d\-]+)\.naobzore/)
    @company = Site.find_by_subdomen(m[1]).try(:company) || Subdomain.find_by_name(m[1]).try(:company)
    return render :text => 'Сайт не активирован' unless @company.status == :active
  end

  protected

  def add_meta
    if @entity
      meta :description, @entity.description        
      link :image_src, @entity.image_url
      meta :property => 'og:title', :content => @entity.name
      meta :property => 'og:description', :content => @entity.description
      meta :property => 'og:image', :content => @entity.image_url
      meta :property => 'og:url', :content => "http://#{request.domain}#/#{@entity.class.to_s.downcase}/#{@entity.id}"
    end
  end
end

app/controllers/minisite/feedbacks_controller.rb
class Minisite::FeedbacksController < Minisite::BaseController
  before_filter :find_feedback, :only => [:like, :ignore, :favorite]
  include Likes

  private

  def find_feedback
    @entity = @feedback = Feedback.find params[:id]
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/company_panel/campaigns_helper.rb
module CompanyPanel::CampaignsHelper
end

app/helpers/minisite/campaigns_helper.rb
module Minisite::CampaignsHelper
end

app/helpers/minisite/comments_helper.rb
module Minisite::CommentsHelper
end

app/views/minisite/campaigns/_campaign.html.erb
<div class="campaign">
  <div class="data-container">
      <div class="left">
           <a href="<%= campaign_path campaign %>"><img src="<%= campaign.main_photo.try(:url, :thumb) %>" alt="" /></a>
      </div>
      <div class="right">
          <!--Заголовочек-->
          <div class="ext-title">
              <a href="<%= campaign_path campaign %>"><%= campaign.name %></a>
              <p><%= l campaign.start_at, :format => '%d %B %Y' %> года</p>
              <div class="clear"></div>
          </div>
          <!--Заголовочек-->
          <div class="text">
            <%=raw campaign.description %>
          </div>
      </div>
      <div class="clear"></div>
  </div>
  <div class="footer">
      <div class="comments-count">
          <div class="l"></div>
          <div class="r"><a href="#" class="show-comments">Комментариев (<%= campaign.comments_count %>)</a></div>
          <div class="clear"></div>
      </div>
      <%= render :partial => 'minisite/shared/likes', :locals => { :entity => campaign } %>
  </div>
  <%= render :partial => 'minisite/comments/comments_block', :locals => { :entity => campaign, :comments => campaign.comments.last(Comment::LAST_COUNT), :visible => false } %>
</div>

app/views/minisite/campaigns/index.html.erb
<!-- Блок с заголовком -->
<div class="entity-title">
    <h2>Акции</h2>
    <p></p>
    <div class="clear"></div>
</div>

<!-- Блок с фильтрами -->
<div class="filters">
    <!--Левый блок-->
    <div class="left">
        <div class="row">
            <div class="cell left">Сортировать по</div>
            <div class="cell right">
                <select class="selectbox">
                  <option value="created_at">Дате добавления</option>
                  <option value="feedbacks_count">Комментариям</option>
                  <option value="views">Популярности</option>
                </select>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <!--Центральный блок-->
    <div class="center">
        <div class="row">
            
        </div>
    </div>
    <!--Правый блок-->
    <div class="right">
        <div class="row">
            <ul class="count-page">
                <li>Показать:</li>
                <% [10,20,30].each do |per_page| %>
                  <li><%= link_to per_page.to_s, params.merge(:per_page => per_page, :format => :js), :remote => true, :class => (params[:per_page] == per_page || per_page == 20 && params[:per_page].blank?) ? 'active' : '' %></li>
                <% end %>
            </ul>
        </div>
    </div>
<div class="clear"></div>
</div>
<div class="found-res text-center" style="display: none;">
	<span class="found-res-btn">
		Показать 100 результатов
	</span>
</div>

<!-- Блок с подписаться и управлением колличеством элементов -->
<div class="sub-filters">
    <div class="left">
      <%= render :partial => 'minisite/shared/subscribe' %>
    </div>
    <div class="right">
        <!-- Чтонить сюда можно воткнуть -->
    </div>
    <div class="clear"></div>
</div>


<div class="campaigns">
	<% if @campaigns.count > 0 %>
		<%= render @campaigns %>
	<% else %>
		<div class="empty-content">Акций и скидок нет</div>
	<% end %>
</div>
<%#= will_paginate @campaigns, :renderer => 'BootstrapPaginationHelper::LinkRenderer', :previous_label => '', :next_label => '' %>
<div class="pagination-separator" style="display:none;"><div class="ps-page">Страница <span class="ps-page-num" data-page="1">1</span></div></div>
<a href="#" class="pagination-link">
	Показать еще <%=  !params[:count].blank? ? params[:count] : 10 %>
</a>

app/views/minisite/campaigns/show.html.erb
<div class="entity-title">
    <h2>Акции</h2>
    <p></p>
    <div class="clear"></div>
</div>

<h1 class="blue-title"><%= @campaign.name %></h1>

<div class="entity campaign">
    <div class="header">
        <div class="left">
            <img src="<%= @campaign.image.thumb %>" alt="" />
        </div>
        <div class="right">
            <div class="info">
                <p><a href="#"><%= @company.address %></a></p>
                <p>тел.: <%= @company.phone %></p>
                <p><a class="call-up" href="#"></a></p>
                <%= render :partial => 'minisite/shared/likes', :locals => { :entity => @campaign } %>
            </div>
        </div>
        <div class="clear"></div>
    </div>
    
    
    <!-- Блок отправки акции -->
    <div class="send-campaign hidden" id="sendCampaignBlock">
      <%= form_for @campaign, :url => campaign_send_campaign_path(@campaign), :html => { :remote => true, :method => 'post' } do |f| %>
        <div class="to">
            <input type="text" placeholder="Введите адрес электронной почты" name="campaign[email]" id="campaign_email" />
        </div>
        <div class="buttons">
            <a class="left send" href="#">Отправить</a><a class="right cancel" href="#">Отмена</a>
        </div>
      <% end %>
    </div>
    <!-- end | Блок отправки акции -->
    
    <!--Блок с вкладками-->
    <div class="tabs">
        <ul class="tabs-items">
            <li><a href="#" data-tab="0" class="active">Описание</a></li>
            <li><a href="#" data-tab="popup" id="sendCampaign">Отправить акцию</a></li>
            <li><a href="#" data-tab="2">Комментарии (<%= @campaign.comments_count %>)</a></li>
        </ul>
        <div class="tabs-content">
            
        <!--Описание-->
            <div class="tab-content" data-tab="0">
                <p class="campaign-description">
                  <%=raw @campaign.description %>
                </p>
            </div>
        <!--Отправить акцию-->
            <div class="tab-content" data-tab="1">
                
            </div>
        <!--Комменарии-->
            <div class="tab-content hidden" data-tab="2">
              <%= render :partial => 'minisite/comments/comments_block', :locals => { :entity => @campaign, :comments => @campaign.comments.last(Comment::LAST_COUNT) } %>
            </div>
            
        </div>
    </div>
    
		<%= render :partial => 'minisite/shared/footer_sharing', :locals => { :entity => @campaign } %>
    
</div>