config/routes.rb
class CategoryConstraints
  def self.matches? request
    !Category.find_by_alias(request.path_parameters[:category]).nil?
  end
end

class PageLinkConstraints
  def self.matches? request
    !Page.find_by_link(request.path_parameters[:link]).nil?
  end
end

class CompanySubdomainConstraints
  def self.matches? request
    !!(m = request.server_name.match(/^([\w\d\-]+)\.naobzore/) and (Site.find_by_subdomen(m[1]).try(:company) || Subdomain.find_by_name(m[1]).try(:company)))
  end
end

OnshowLoc::Application.routes.draw do
  def likes
    post :like
    post :ignore
    post :favorite
  end

  scope :module => "minisite" do
    constraints CompanySubdomainConstraints do
      root :to => 'home#index'
      resources :goods, :only => [:index, :show] do
        member do
          likes
        end
      end
      resources :services, :only => [:index, :show] do
        member do
          likes
        end
      end
      resources :users, :only => [] do
        member do
          put :subscribe
        end
      end
      resources :news, :only => [] do
        resources :comments, :only => [:index, :create]
        member do
          likes
        end
      end
      get '/news' => 'news#index'
      get '/news/:id' => 'news#show'
      resources :campaigns, :only => [:index, :show] do
        member do
          post :campaign_send
          likes
        end
        resources :comments, :only => [:index, :create]
      end
      get '/about' => 'home#about', :as => :about
      get '/contacts' => 'home#contacts', :as => :contacts
      get '/search' => 'home#search', :as => :search
      resources :jobs, :only => [:index, :show] do
        resources :comments, :only => [:index, :create]
        member do
          likes
        end
      end
      resources :resumes, :only => [] do
        member do
          post :resume_send
        end
      end
      resources :feedbacks, :only => [] do
        member do
          likes
        end
      end
      resources :messages, :only => :create
    end
  end # minisite

  mount Ckeditor::Engine => '/ckeditor'

  match "favorite/:type/:id/:status" => "favorites#plus"
  get "like/:type/:id" => "likes#add"
  
  get "/cabinet/ajax/:id/:type" => "cabinet#ajax"
  get "/cabinet/switching/:id/:type/:direction/:type_one" => "cabinet#switching"
  get "cabinet/:type" => "cabinet#entities"

  get "/goods/ajax/:id/:type" => "goods#ajax"
  get "/goods/switching/:id/:direction/" => "goods#switching"
  get "/goods/switching/:category/:id/:direction/" => "goods#switching"
  
  get "/services/ajax/:id/:type" => "services#ajax"
  get "/services/switching/:id/:direction/" => "services#switching"
  get "/services/switching/:category/:id/:direction/" => "services#switching"
  
  get "/jobs/ajax/:id/:type" => "jobs#ajax"
  get "/jobs/switching/:id/:direction/" => "jobs#switching"
  get "/jobs/switching/:category/:id/:direction/" => "jobs#switching"
  
  get "/companies/ajax/:id/:type" => "companies#ajax"
  get "/companies/switching/:id/:direction/" => "companies#switching"
  get "/companies/switching/:category/:id/:direction/" => "companies#switching"
  
  get "/campaigns/ajax/:id/:type" => "campaigns#ajax"
  get "/campaigns/switching/:id/:direction/" => "campaigns#switching"
  get "/campaigns/switching/:category/:id/:direction/" => "campaigns#switching"

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  ActiveAdmin.routes(self)
  
  default_url_options :host => "naobzore.ru"

  resources :cabinet

  resources :products

  resources :pages

  resources :banners

  resources :sites
  
  get "help" => "help#index"
  get "help/:category" => "help#index"
  get "help/:alias" => "help#index"
  get "help/show/:alias" => "help#show"
  
  get "/feedbacks" => "feedbacks#index"
  get "/feedbacks/:category" => "feedbacks#index"
  post "/feedbacks/add" => "feedbacks#add"
  
  get "campaigns/" => "campaigns#index"
  get "campaigns/:category" => "campaigns#index", :constraints => CategoryConstraints
  get "campaigns/:id" => "campaigns#show", :as => :campaign
  get "campaigns/:category/:id" => "campaigns#show"
  
  get "news/" => "news#index"
  get "news/:category" => "news#index", :constraints => CategoryConstraints
  get "news/:id" => "news#show", :as => 'show_news'
  get "news/:category/:id" => "news#show"

  get "/companies" => "companies#index"
  get "/companies/:category" => "companies#index"

  get "/jobs" => "jobs#index"
  get "/jobs/:category" => "jobs#index", :constraints => CategoryConstraints
  get "/jobs/:id" => "jobs#show", :as => :job
  get "/jobs/:category/:id" => "jobs#show"
  
  get "/resume" => "resume#index"
  get "/resume/:category" => "resume#index", :constraints => CategoryConstraints
  get "/resume/:id" => "resume#show"
  get "/resume/:category/:id" => "resume#show"

  get "/services" => "services#index"
  get "/services/:category" => "services#index", :constraints => CategoryConstraints
  get "/services/:id" => "services#show", :as => :service
  get "/services/:category/:id" => "services#show"

  get "/goods" => "goods#index"
  get "/goods/:category" => "goods#index", :constraints => CategoryConstraints
  get "/goods/:id" => "goods#show", :as => :good
  get "/goods/:category/:id" => "goods#show"

  resources :categories

  match '/social/export' => 'social#export', :as => :social_export

  namespace :company_panel do
    root :to => 'home#index'

    post '/widgets/save_order' => 'home#save_widgets_order'
    get '/mail' => 'home#mail'
    get '/site_control' => 'home#site_control'
	
	get '/messages/dialog' => 'messages#dialog'

    resources :statistics, :only => [:index]
    resources :news, :only => [:new, :create]
    resources :users, :only => [:edit, :update, :destroy] do
      member do
        get :edit_password
        put :update_password
        get :edit_email
        put :update_email
        get :delete_account
      end
      collection do
        get :search
      end
    end
		resources :messages, :only => [:index, :create]
		resources :resumes, :only => [:index, :show, :destroy] do
			member do
				post :offer
			end
      collection do
        get :search
      end
		end
    resources :subscribes, :only => [:index, :destroy]
    resources :emails, :only => [:index]
    resources :sms, :only => [:index]
    resources :calls, :only => [:index]
    %w(goods services campaigns jobs).each do |r|
      resources r.to_sym, :only => [:index, :new, :create, :edit, :update] do
        collection do
          post :mass_publish
          post :mass_unpublish
          post :mass_destroy
          get :search
        end
        member do
          post :mass_set_photos
          get :load_image
        end
      end
    end
    get '/campaigns/entities' => 'campaigns#entities', :as => 'campaigns_entities'
    resources :price_lists, :only => [:new, :create]
    resources :price_entities, :only => [:index, :update] do
      collection do
        post :mass_destroy
        post :export
      end
      member do
        post :mass_set_photos
        get :load_image
      end
    end
    get '/pages/:link' => 'pages#show', :constraints => PageLinkConstraints, :as => :page
    resources :categories, :only => [:index]
    resources :photos, :only => [:index, :create, :update, :destroy] do
      collection do
        post :mass_destroy
        get :entities
      end
    end
    resources :packages, :only => [] do
      collection do
        get :placing
        get :communication
      end
    end
    resources :companies_packages, :only => [:create] do
      member do
        post :set_auto
      end
    end
    resources :banners, :only => [:new, :create]
    resources :companies, :only => [:edit, :update] do
      member do
        get :legal
        get :logotype
        get :tmp_logotype
        get :schedule
        get :crediting
      end
    end
    resources :banks
    resources :companies_users, :only => [:index, :create, :destroy] do
      collection do
        get :search
        get :user_by_email
        put :user_phone_email
        post :invite
      end
    end
    resources :deliveties, :warranties
    resources :menus, :only => [:index] do
      collection do
        post :set_order
      end
    end
    resources :subdomains, :only => [:index] do
      collection do
        post :mass_save
      end
    end
    resources :sites, :only => [:update] do
      member do
        get :stats
        get :webmaster
        get :sitemap
        get :robots
        get :construct
        put :commit
      end
    end
    resources :invoices do
      member do
        put :pay
      end
      collection do
        get :movement
      end
    end
    resources :factures
    resources :acts
    resources :tutorials, :only => [:index]
    resources :feedbacks, :only => [:index]
    resources :companies_resumes, :only => [:index, :destroy] do
      member do
        post :change_status
      end
      collection do
        post :mass_reject
        delete :mass_destroy
      end
    end
    resources :notifications, :only => [:index]
    resources :folders
  end

  root :to => 'home#index'

end

app/controllers/company_panel/acts_controller.rb
# encoding: utf-8

class CompanyPanel::ActsController < CompanyPanel::BaseController
  def index
    @acts = @company.acts.order("id DESC").paginate(:page => params[:page] || 1, :per_page => @per_page)
    Act.mark_as_read! @acts.to_a, :for => current_user
  end

  def show
    @act = @company.acts.find params[:id]
    @act.mark_as_read! :for => current_user
    @main_company = Company.main
    respond_to do |format|
      format.html {}
      format.pdf { render :pdf => @act.pdf_name, :layout => false, :template => 'company_panel/acts/show.html.erb' }
    end
  end

  private

  def set_widgets
    super.unshift(:balance)
  end
end

app/controllers/company_panel/banks_controller.rb
# encoding: utf-8

class CompanyPanel::BanksController < CompanyPanel::BaseController
  before_filter :find_bank, :only => [:edit, :update, :destroy]
  before_filter :set_phone, :only => [:create, :update]

  def index
    @banks = Bank.all
    redirect_to new_company_panel_bank_path if @banks.empty?
  end

  def new
    @bank = Bank.new
  end

  def create
    @bank = Bank.new params[:bank]
    if @bank.save
      redirect_to company_panel_banks_path
    else
      render :index
    end
  end

  def edit
  end

  def update
    if @bank.update_attributes(params[:bank])
      redirect_to company_panel_banks_path
    else
      render :index
    end
  end

  def destroy
    @bank.destroy
    redirect_to company_panel_banks_path
  end

  private

  def find_banks
  end

  def find_bank
    @bank = Bank.find params[:id]
  end

  def set_phone
    unless params[:phone_code].blank? && params[:phone_number].blank?
      params[:bank]['phone'] = "+7(#{params[:phone_code]})#{params[:phone_number]}"
    end
  end

  def set_widgets
    super
    @menu_controller = 'company_panel/deliveties'
  end
end

app/controllers/company_panel/banners_controller.rb
# encoding: utf-8

class CompanyPanel::BannersController < CompanyPanel::BaseController
  def new
    @banner = Banner.new
  end

  def set_widgets
    @widgets = [:menu, :support_service]
    @menu_title = current_user.company.human_balance 
  end

  def create
    @weeks = JSON.parse(params[:weeks])
    sum = @weeks.values.flatten.compact.count * Banner.week_price

    success = true
    Banner.transaction do
      @weeks.each do |type, weeks|
        weeks.each do |week|
          @banner = Banner.new(params[:banner].merge(:banner_type => type, :week => week, :company_id => @company.id))
          success = false and break(2) unless @banner.save
        end
      end
    end
    
    if success
      unless (invoice = @company.invoices.build(:sum => sum, :entity_type => 'Banner', :status => :complete)).save
        return redirect_to :back, :notice => invoice.errors.full_messages.join('<br />')
      end
      redirect_to new_company_panel_banner_path
    else
      render :new
    end
  end
end

app/controllers/company_panel/base_controller.rb
# coding: utf-8

class CompanyPanel::BaseController < ActionController::Base
  before_filter :authenticate_user!
  before_filter :find_company
  before_filter :set_widgets
  before_filter :set_per_page, :only => [:index]
  
  #Опции
  layout "company_panel/layouts/company_panel"

  def find_company
    @company = current_user.account
  end

  def set_widgets
    @widgets = [:menu, :support_service]
  end

  def set_per_page
    @per_page = if params[:per_page].to_i > 0
      cookies[:per_page] = params[:per_page].to_i
    elsif cookies[:per_page].to_i > 0
      cookies[:per_page].to_i
    else
      CONFIG[:per_page]
    end
  end
end

app/controllers/company_panel/calls_controller.rb
class CompanyPanel::CallsController < CompanyPanel::BaseController
  def index
  end
end

app/controllers/company_panel/campaigns_controller.rb
# encoding: utf-8

class CompanyPanel::CampaignsController < CompanyPanel::EntitiesController
  def initialize
    super
    @entity_type = 'Campaign'
  end

  def create
    super
  end

  def update
    %w(start_at end_at).each do |field|
      params[:entity][field] = DateTime.parse(params[:entity][field]) if params[:entity][field]
    end
    super
  end

  def new
    @entity = @entity_type.constantize.new(:company_id => @company.id, :end_at => Time.now + 1.month)
    @service = Good.limit(10)
    @service += Service.limit(10)
    @h1 = 'Добавление акции/скидки'
  end

  def edit
    super
    @h1 = 'Редактирование акции/скидки'
  end

  def entities
    entity_types = %w(Good Service)
    @entities = entity_types.map { |entity_type| entity_type.constantize.where(:article => params[:q]) }.flatten
    @entities = entity_types.map { |entity_type| entity_type.constantize.where('name LIKE ?', "%#{params[:q]}%").limit(10) }.flatten if @entities.empty?
    render :json => @entities.map { |entity| entity.as_json.merge({ :entity_type => entity.class.to_s })}
  end
end

app/controllers/company_panel/categories_controller.rb
class CompanyPanel::CategoriesController < CompanyPanel::BaseController
  def index

  end
end

app/controllers/company_panel/companies_controller.rb
# encoding: utf-8

class CompanyPanel::CompaniesController < CompanyPanel::BaseController
  before_filter :find_company
  before_filter :save_action

  def edit
  end

  def legal
  end

  def logotype
  end

  def tmp_logotype
    render :layout => false
  end

  def schedule
  end

  def crediting
  end

  def update
    if params[:phone_number]
      phone = []
      params[:phone_number].each_with_index do |phone_number, index|
        unless phone_number.blank?
          phone << "+7(#{params[:phone_code][index].gsub(/\D/, '')})#{phone_number}" + (params[:phone_dob][index].blank? ? '' : "(#{params[:phone_dob][index]})")
        end
      end
      params[:company]['phone'] = phone.join(';')
    end

    if params[:fax_number]
      fax = []
      params[:fax_number].each_with_index do |fax_number, index|
        unless fax_number.blank?
          fax << "+7(#{params[:fax_code][index].gsub(/\D/, '')})#{fax_number}"
        end
      end
      params[:company]['fax'] = fax.join(';')
    end

    %w(settlement_account post_index icq creation_year bik kpp bank_cor_account).each do |field|
      if params[:company][field]
        params[:company][field].gsub!(/\D/, '')
      end
    end

    success = if params[:company]['logotype']
      ActiveRecord::Base.connection.execute(ActiveRecord::Base.send(:sanitize_sql_array, [
        "UPDATE companies SET logotype = ?, tmp_logotype = NULL WHERE id = ?", File.basename(params[:company]['logotype']), @company.id
      ]))
      true
    else 
      @company.update_attributes(params[:company])
    end
    respond_to do |format|
      format.html do
        if success
          redirect_to :controller => session['current_controller'], :action => session['current_action'], :id => @company.id
        else
          render session['current_action']
        end
      end
      format.json do
        if success
          render :json => { :success => true, :company => @company.to_json }
        else
          render :json => { :success => false, :errors => @company.errors.full_messages.to_json }
        end
      end
    end
  end

  private

  def find_company
    @company = current_user.account
  end

  def save_action
    session['current_controller'] = params[:controller] if request.method == 'GET'
    session['current_action'] = params[:action] if request.method == 'GET'
  end
end

app/controllers/company_panel/companies_packages_controller.rb
class CompanyPanel::CompaniesPackagesController < CompanyPanel::BaseController
  def create
    @package = Package.find params[:companies_package]['package_id']
    params[:companies_package]['start_at'] = Time.now
    months = params[:companies_package]['end_at'].to_i.months
    months = 3.months if months <= 0
    params[:companies_package]['end_at'] = Time.now + months
    params[:companies_package]['company_id'] = current_user.account.id
    @companies_package = CompaniesPackage.new(params[:companies_package])
    @res = @companies_package.save
  end

  def set_auto
    @companies_package = CompaniesPackage.find params[:id]
    @companies_package.update_attribute(:auto, params[:auto])
    @package = @companies_package.package
  end
end

app/controllers/company_panel/emails_controller.rb
# encoding: utf-8

class CompanyPanel::EmailsController < CompanyPanel::BaseController
  def index
    @emails = Email.order('id desc').paginate(:page => params[:page] || 1, :per_page => @per_page)
  end
end

app/controllers/company_panel/feedbacks_controller.rb
class CompanyPanel::FeedbacksController < CompanyPanel::BaseController
  def index
    @feedbacks = Feedback.order('id desc').paginate(:page => params[:page])
  end
end

app/views/company_panel/companies_resumes/_companies_resume.html.erb
<tr data-entity_id="<%= companies_resume.id %>">
  <td style="width:20px;"><input type="checkbox" class="row-checkbox" /></td>
  <td><%= link_to companies_resume.job.name, edit_company_panel_job_path(companies_resume.job_id) if companies_resume.job %></td>
  <td><%= link_to companies_resume.resume.name, company_panel_resume_path(companies_resume.resume_id) %></td>
  <td><%= link_to companies_resume.resume.user.fio, edit_company_panel_user_path(companies_resume.resume.user_id) %></td>
  <td><%= t "companies_resumes.statuses.#{companies_resume.status}" %></td>
  <td>
    <%= link_to_unless companies_resume.status == :responded, 'Ответить', '#', :class => "view-popup", 'data-type' => "send-message", 'data-to_id' => companies_resume.resume.user_id, 'data-title' => "Сообщение пользователю \"#{companies_resume.resume.user.fio}\"", 'data-action' => change_status_company_panel_companies_resume_path(companies_resume, :format => :js, :companies_resume => { :status => :responded }), :title => "Написать сообщение" %>
    <%= link_to_unless companies_resume.status == :rejected, 'Отказать', change_status_company_panel_companies_resume_path(companies_resume, :format => :js, :companies_resume => { :status => :rejected }), :method => :post, :remote => true, :confirm => "Отказать пользователю \"#{companies_resume.resume.user.fio}\"?", :title => 'Отказать' %>
    <%= link_to 'Удалить', company_panel_companies_resume_path(companies_resume), :method => :delete, :confirm => "Удалить заявку пользователя \"#{companies_resume.resume.user.fio}\"?", :title => 'Удалить' %>
  </td>
</tr>

app/views/company_panel/companies_resumes/_tabs.html.erb
<ul class="reload-tabs">
  <% [["Заявки по вакансиям#{counter(@company.companies_resumes.with_job_id.where(:status => :new).count)}", company_panel_companies_resumes_path(:with_job_id => true, :status => :new), params[:with_job_id].present?], ["Все резюме#{counter(@company.companies_resumes.where(:status => :new).count)}", company_panel_companies_resumes_path, params[:with_job_id].blank?]].each_with_index do |(name, href, active), index| %>
    <li>
      <% if active %>
        <a href="#" data-id="<%= index + 1 %>" class="active"><%= name %></a>
      <% else %>
        <%= link_to name, href, 'data-id' => index + 1 %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/company_panel/companies_resumes/change_status.js.erb
<% if @companies_resume.status == :rejected %>
  document.location.reload();
<% elsif @success %>
  $('#new_message #error_explanation').html('');
  $('#new_message #message_text').val('');
  $('#new_message #message_subject').val('');
  $('.popup[data-type="send-message"] .close').click();
  document.location.reload();
<% else %>
  $('#new_message #error_explanation').replaceWith('<%= raw escape_javascript(render_error_explanation @message) %>');
<% end %>

app/views/company_panel/companies_resumes/index.html.erb
<div class="list">
  <%= render :partial => 'tabs' %>
  <div class="content">
    <div class="tab-content" data-id="1">
      <div class="kegrid-wrap">
        <table class="kegrid style-silver" cellpadding="0" cellspacing="0">
          <thead>
            <tr>
              <th><input type="checkbox" class="checked-all" /></th>
              <th>Резюме</th>
               <% if params[:status] %><th>Вакансия</th><% end %>
              <th>Пользователь</th>
              <th>Статус</th>
              <th></th>
              <!--<th>Деятельность компании</th>-->
            </tr>
          </thead>
          <tbody>
            <%= render :partial => 'companies_resume', :collection => @companies_resumes %>
          </tbody>
        </table>
	  </div>
	  
	  <div class="flr"><br>
		<input class="blue-button" type="submit" value="Сохранить">
	  </div>
      
      <!-- Подвальчик -->
      <footer class="footer">
        <div class="element">
          <img src="/controlPanel/images/checkbox.png" /> <span id="checkedCount">0</span>
        </div>
        <div class="element">
          <select class="mass-action">
            <option>Массовые действия</option>
            <option value="reject">Отказать</option>
            <option value="destroy">Удалить</option>
          </select>
        </div>
        <%= render :partial => 'company_panel/shared/pagination', :locals => {:obj => @companies_resumes} %>
      </footer>
    </div>
    
    <div class="tab-content hidden" data-id="2">
      <!--j-->
      <div class="footer">
        <!--FOOOOOTEEERRR-->
      </div>
    </div>
    
    <div class="tab-content hidden" data-id="3">
      <!--s-->
      <div class="footer">
        <!--FOOOOOTEEERRR-->
      </div>
    </div>
    
    <div class="tab-content hidden" data-id="4">
      <!--c-->
      <div class="footer">
        <!--FOOOOOTEEERRR-->
      </div>
    </div>
    
  </div>
</div>