config/routes.rb
class CategoryConstraints
  def self.matches? request
    !Category.find_by_alias(request.path_parameters[:category]).nil?
  end
end

class PageLinkConstraints
  def self.matches? request
    !Page.find_by_link(request.path_parameters[:link]).nil?
  end
end

class CompanySubdomainConstraints
  def self.matches? request
    !!(m = request.server_name.match(/^([\w\d\-]+)\.naobzore/) and (Site.find_by_subdomen(m[1]).try(:company) || Subdomain.find_by_name(m[1]).try(:company)))
  end
end

OnshowLoc::Application.routes.draw do
  def likes
    post :like
    post :ignore
    post :favorite
  end

  scope :module => "minisite" do
    constraints CompanySubdomainConstraints do
      root :to => 'home#index'
      resources :goods, :only => [:index, :show] do
        member do
          likes
        end
      end
      resources :services, :only => [:index, :show] do
        member do
          likes
        end
      end
      resources :users, :only => [] do
        member do
          put :subscribe
        end
      end
      resources :news, :only => [] do
        resources :comments, :only => [:index, :create]
        member do
          likes
        end
      end
      get '/news' => 'news#index'
      get '/news/:id' => 'news#show'
      resources :campaigns, :only => [:index, :show] do
        member do
          post :campaign_send
          likes
        end
        resources :comments, :only => [:index, :create]
      end
      get '/about' => 'home#about', :as => :about
      get '/contacts' => 'home#contacts', :as => :contacts
      get '/search' => 'home#search', :as => :search
      resources :jobs, :only => [:index, :show] do
        resources :comments, :only => [:index, :create]
        member do
          likes
        end
      end
      resources :resumes, :only => [] do
        member do
          post :resume_send
        end
      end
      resources :feedbacks, :only => [] do
        member do
          likes
        end
      end
      resources :messages, :only => :create
    end
  end # minisite

  mount Ckeditor::Engine => '/ckeditor'

  match "favorite/:type/:id/:status" => "favorites#plus"
  get "like/:type/:id" => "likes#add"
  
  get "/cabinet/ajax/:id/:type" => "cabinet#ajax"
  get "/cabinet/switching/:id/:type/:direction/:type_one" => "cabinet#switching"
  get "cabinet/:type" => "cabinet#entities"

  get "/goods/ajax/:id/:type" => "goods#ajax"
  get "/goods/switching/:id/:direction/" => "goods#switching"
  get "/goods/switching/:category/:id/:direction/" => "goods#switching"
  
  get "/services/ajax/:id/:type" => "services#ajax"
  get "/services/switching/:id/:direction/" => "services#switching"
  get "/services/switching/:category/:id/:direction/" => "services#switching"
  
  get "/jobs/ajax/:id/:type" => "jobs#ajax"
  get "/jobs/switching/:id/:direction/" => "jobs#switching"
  get "/jobs/switching/:category/:id/:direction/" => "jobs#switching"
  
  get "/companies/ajax/:id/:type" => "companies#ajax"
  get "/companies/switching/:id/:direction/" => "companies#switching"
  get "/companies/switching/:category/:id/:direction/" => "companies#switching"
  
  get "/campaigns/ajax/:id/:type" => "campaigns#ajax"
  get "/campaigns/switching/:id/:direction/" => "campaigns#switching"
  get "/campaigns/switching/:category/:id/:direction/" => "campaigns#switching"

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  ActiveAdmin.routes(self)
  
  default_url_options :host => "naobzore.ru"

  resources :cabinet

  resources :products

  resources :pages

  resources :banners

  resources :sites
  
  get "help" => "help#index"
  get "help/:category" => "help#index"
  get "help/:alias" => "help#index"
  get "help/show/:alias" => "help#show"
  
  get "/feedbacks" => "feedbacks#index"
  get "/feedbacks/:category" => "feedbacks#index"
  post "/feedbacks/add" => "feedbacks#add"
  
  get "campaigns/" => "campaigns#index"
  get "campaigns/:category" => "campaigns#index", :constraints => CategoryConstraints
  get "campaigns/:id" => "campaigns#show", :as => :campaign
  get "campaigns/:category/:id" => "campaigns#show"
  
  get "news/" => "news#index"
  get "news/:category" => "news#index", :constraints => CategoryConstraints
  get "news/:id" => "news#show", :as => 'show_news'
  get "news/:category/:id" => "news#show"

  get "/companies" => "companies#index"
  get "/companies/:category" => "companies#index"

  get "/jobs" => "jobs#index"
  get "/jobs/:category" => "jobs#index", :constraints => CategoryConstraints
  get "/jobs/:id" => "jobs#show", :as => :job
  get "/jobs/:category/:id" => "jobs#show"
  
  get "/resume" => "resume#index"
  get "/resume/:category" => "resume#index", :constraints => CategoryConstraints
  get "/resume/:id" => "resume#show"
  get "/resume/:category/:id" => "resume#show"

  get "/services" => "services#index"
  get "/services/:category" => "services#index", :constraints => CategoryConstraints
  get "/services/:id" => "services#show", :as => :service
  get "/services/:category/:id" => "services#show"

  get "/goods" => "goods#index"
  get "/goods/:category" => "goods#index", :constraints => CategoryConstraints
  get "/goods/:id" => "goods#show", :as => :good
  get "/goods/:category/:id" => "goods#show"

  resources :categories

  match '/social/export' => 'social#export', :as => :social_export

  namespace :company_panel do
    root :to => 'home#index'

    post '/widgets/save_order' => 'home#save_widgets_order'
    get '/mail' => 'home#mail'
    get '/site_control' => 'home#site_control'
	
	get '/messages/dialog' => 'messages#dialog'

    resources :statistics, :only => [:index]
    resources :news, :only => [:new, :create]
    resources :users, :only => [:edit, :update, :destroy] do
      member do
        get :edit_password
        put :update_password
        get :edit_email
        put :update_email
        get :delete_account
      end
      collection do
        get :search
      end
    end
		resources :messages, :only => [:index, :create]
		resources :resumes, :only => [:index, :show, :destroy] do
			member do
				post :offer
			end
      collection do
        get :search
      end
		end
    resources :subscribes, :only => [:index, :destroy]
    resources :emails, :only => [:index]
    resources :sms, :only => [:index]
    resources :calls, :only => [:index]
    %w(goods services campaigns jobs).each do |r|
      resources r.to_sym, :only => [:index, :new, :create, :edit, :update] do
        collection do
          post :mass_publish
          post :mass_unpublish
          post :mass_destroy
          get :search
        end
        member do
          post :mass_set_photos
          get :load_image
        end
      end
    end
    get '/campaigns/entities' => 'campaigns#entities', :as => 'campaigns_entities'
    resources :price_lists, :only => [:new, :create]
    resources :price_entities, :only => [:index, :update] do
      collection do
        post :mass_destroy
        post :export
      end
      member do
        post :mass_set_photos
        get :load_image
      end
    end
    get '/pages/:link' => 'pages#show', :constraints => PageLinkConstraints, :as => :page
    resources :categories, :only => [:index]
    resources :photos, :only => [:index, :create, :update, :destroy] do
      collection do
        post :mass_destroy
        get :entities
      end
    end
    resources :packages, :only => [] do
      collection do
        get :placing
        get :communication
      end
    end
    resources :companies_packages, :only => [:create] do
      member do
        post :set_auto
      end
    end
    resources :banners, :only => [:new, :create]
    resources :companies, :only => [:edit, :update] do
      member do
        get :legal
        get :logotype
        get :tmp_logotype
        get :schedule
        get :crediting
      end
    end
    resources :banks
    resources :companies_users, :only => [:index, :create, :destroy] do
      collection do
        get :search
        get :user_by_email
        put :user_phone_email
        post :invite
      end
    end
    resources :deliveties, :warranties
    resources :menus, :only => [:index] do
      collection do
        post :set_order
      end
    end
    resources :subdomains, :only => [:index] do
      collection do
        post :mass_save
      end
    end
    resources :sites, :only => [:update] do
      member do
        get :stats
        get :webmaster
        get :sitemap
        get :robots
        get :construct
        put :commit
      end
    end
    resources :invoices do
      member do
        put :pay
      end
      collection do
        get :movement
      end
    end
    resources :factures
    resources :acts
    resources :tutorials, :only => [:index]
    resources :feedbacks, :only => [:index]
    resources :companies_resumes, :only => [:index, :destroy] do
      member do
        post :change_status
      end
      collection do
        post :mass_reject
        delete :mass_destroy
      end
    end
    resources :notifications, :only => [:index]
    resources :folders
  end

  root :to => 'home#index'

end

app/controllers/minisite/base_controller.rb
# encoding: utf-8

class Minisite::BaseController < ApplicationController
  before_filter :find_company_by_subdomain
  before_filter lambda { @site = @company.site }
  before_filter lambda { @construct_mode = !!params[:construct_mode] }

  layout 'minisite'

  def find_company_by_subdomain
    m = request.server_name.match(/^([\w\d\-]+)\.naobzore/)
    @company = Site.find_by_subdomen(m[1]).try(:company) || Subdomain.find_by_name(m[1]).try(:company)
    return render :text => 'Сайт не активирован' unless @company.status == :active
  end

  protected

  def add_meta
    if @entity
      meta :description, @entity.description        
      link :image_src, @entity.image_url
      meta :property => 'og:title', :content => @entity.name
      meta :property => 'og:description', :content => @entity.description
      meta :property => 'og:image', :content => @entity.image_url
      meta :property => 'og:url', :content => "http://#{request.domain}#/#{@entity.class.to_s.downcase}/#{@entity.id}"
    end
  end
end

app/controllers/minisite/campaigns_controller.rb
# encoding: utf-8

class Minisite::CampaignsController < Minisite::BaseController
  before_filter :find_campaign, :only => [:show, :campaign_send, :like, :ignore, :favorite]
  before_filter :add_meta
  include Likes

  def index
    @campaigns = @company.campaigns
    @campaigns = @campaigns.for_user(current_user) if user_signed_in?
    @campaigns = @campaigns.order(case params[:order]
      when 'comments_count' then 'comments_count desc'
      when 'views' then 'views desc'
      else 'id desc'
    end).paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 20)
    add_breadcrumb 'Акции'
  end

  def show
    add_breadcrumb 'Акции', campaigns_path
    add_breadcrumb @campaign.name
  end

  def campaign_send
    unless !params[:campaign] || params[:campaign]['email'].blank?
      CampaignsMailer.campaign_send(@campaign, params[:campaign]['email']).deliver
      render :text => 'ok'
    else
      render :text => 'error'
    end
  end

  private

  def find_campaign
    @entity = @campaign = @company.campaigns.find_by_translit! params[:id]
  end
end

app/controllers/minisite/comments_controller.rb
class Minisite::CommentsController < Minisite::BaseController
  def index
    @entity = case
      when params[:job_id] then Job.find params[:job_id]
      when params[:news_id] then News.find params[:news_id]
      when params[:campaign_id] then Campaign.find params[:campaign_id]
    end
    @comments = @entity.comments
  end

  def create
    @comment = Comment.create(params[:comment])
    @comments = @comment.entity.comments.last(Comment::LAST_COUNT)
  end
end

app/controllers/minisite/entities_controller.rb
class Minisite::EntitiesController < Minisite::BaseController
  before_filter :authenticate_user!, :only => [:like, :ignore, :favorite]
  before_filter :set_entity_type
  before_filter :find_entity, :only => [:show, :like, :ignore, :favorite]
  before_filter :add_meta
  include Likes

  def index
    @entities = @company.send(@entity_type.tableize.to_sym)
    @min_price = @entities.map(&:price).compact.min
    @max_price = @entities.map(&:price).compact.max
    @entities = @entities.where('price >= ? AND price <= ?', params[:min_price].to_i, params[:max_price].to_i) if params[:min_price] && params[:max_price]
    @entities = @entities.with_campaign if params[:with_campaign] && @entities.respond_to?(:with_campaign)
    @entities = @entities.for_user(current_user) if user_signed_in?
    @entities = @entities.where(:category_id => params[:category_id]) if params[:category_id].present?
    @entities = @entities.order(case params[:order]
      when 'feedbacks_count' then 'feedbacks_count desc'
      when 'views' then 'views desc'
      else 'created_at desc'
    end)
    @entities = @entities.paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 20)
  end

  def show
  end

  protected
  
  def set_entity_type
    raise NotImplementedError
  end

  def find_entity
    @entity = @entity_type.constantize.find_by_translit! params[:id]
  end
end

app/controllers/minisite/feedbacks_controller.rb
class Minisite::FeedbacksController < Minisite::BaseController
  before_filter :find_feedback, :only => [:like, :ignore, :favorite]
  include Likes

  private

  def find_feedback
    @entity = @feedback = Feedback.find params[:id]
  end
end

app/controllers/minisite/goods_controller.rb
# encoding: utf-8

class Minisite::GoodsController < Minisite::EntitiesController
  def index
    super
    add_breadcrumb 'Товары'
  end
  
  def show
    super
    add_breadcrumb 'Товары', goods_path
    add_breadcrumb @entity.name
  end
  
  private

  def set_entity_type
    @entity_type = 'Good'
  end
end

app/controllers/minisite/home_controller.rb
# encoding: utf-8

class Minisite::HomeController < Minisite::BaseController
  def index
    @entities = (@company.goods.for_user(try(:current_user)) + @company.services.for_user(try(:current_user))).sample(8)
    @bottom_entities_title, @bottom_entities = if (@campaigns = @company.campaigns.for_user(try(:current_user)).order('start_at DESC').limit(4)).any?
      ['Акции', @campaigns]
    elsif (@jobs = @company.jobs.for_user(try(:current_user)).order('salary_from DESC').limit(4)).any?
      ['Вакансии', @jobs]
    elsif (@news = @company.news.for_user(try(:current_user)).order('id DESC').limit(4)).any?
      ['Новости', @news]
    end
  end

  def about
    add_breadcrumb 'О компании'
  end
  
  def contacts
    add_breadcrumb 'Контакты'
  end

  def search
    add_breadcrumb 'Поиск'
    results = []
    [ :goods, :services, :jobs, :campaigns, :news, :feedbacks ].each do |collection|
      instance_variable_set("@#{collection}", collection.to_s.classify.constantize.where("name LIKE ?", "%#{params[:q]}%"))
      instance_variable_set("@#{collection}", instance_variable_get("@#{collection}").where('maker = ?', params[:maker])) if [:goods, :services].include?(collection) && params[:maker].present?
      results << instance_variable_set("@#{collection}", instance_variable_get("@#{collection}").order("#{params[:order] && collection.to_s.classify.constantize.new.attributes.has_key?(params[:order]) ? params[:order] : 'id'} desc").paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 20))
    end
    render 'empty_search' if results.flatten.empty?
  end
end

app/controllers/minisite/jobs_controller.rb
# encoding: utf-8

class Minisite::JobsController < Minisite::BaseController
  before_filter :find_job, :only => [:show, :like, :ignore, :favorite]
  before_filter :add_meta
  include Likes

  def index
    @salary_from = @company.jobs.select('min(salary_from) as salary_from').first.salary_from
    @salary_to = @company.jobs.select('max(salary_to) as salary_to').first.salary_to
    @jobs = @company.jobs
    @jobs = @jobs.where('salary_to >= :f OR (salary_to IS NULL AND salary_from >= :f)', :f => params[:salary_from]) if params[:salary_from]
    @jobs = @jobs.where('salary_from <= ?', params[:salary_to]) if params[:salary_to]
    @jobs = @jobs.where(:graphic_id => params[:graphic_id]) if params[:graphic_id]
    @jobs = @jobs.for_user(current_user) if user_signed_in?
    @jobs = @jobs.order(case params[:order]
      when 'comments_count' then 'comments_count'
      when 'views' then 'views'
      else 'salary_from'
    end)
    @jobs = @jobs.paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 20)
    add_breadcrumb 'Вакансии'
  end

  def show
    add_breadcrumb 'Вакансии', jobs_path
    add_breadcrumb @job.name
  end

  private

  def find_job
    @entity = @job = @company.jobs.find_by_translit! params[:id]
  end
end

app/controllers/minisite/messages_controller.rb
# encoding: utf-8

class Minisite::MessagesController < Minisite::BaseController
  def create
		respond_to do |format|
			format.js do
        to_id = params[:message].delete('to_id')
				@message = Message.new(params[:message])
        @success = @message.save
        if to_id.present?
          @message.receivers << User.find_by_id(to_id)
        end
			end
		end
	end
end

app/helpers/minisite/campaigns_helper.rb
module Minisite::CampaignsHelper
end

app/helpers/minisite/comments_helper.rb
module Minisite::CommentsHelper
end

app/helpers/minisite/entities_helper.rb
module Minisite::EntitiesHelper
end

app/helpers/minisite/goods_helper.rb
module Minisite::GoodsHelper
end

app/helpers/minisite/jobs_helper.rb
module Minisite::JobsHelper
end

app/helpers/minisite/news_helper.rb
module Minisite::NewsHelper
end

app/helpers/minisite/resumes_helper.rb
module Minisite::ResumesHelper
end

app/views/layouts/minisite/_top_panel.html.erb
<div id="topPanel">
  <header>
      <div class="left"></div>
      <div class="right"></div>
      <div class="content">
      
        <div class="logotype"><a href="http://naobzore.ru/"><img src="/miniSite/images/logo.png" alt="" /></a></div>
         
        <% # TODO Заполнение селектов Катаог и Категория %>
        <%= form_for :search, :url => search_path, :html => { :method => :get } do |f| %>
          <div class="search">
              <div class="container">
                  <div class="field">
                      <span class="icon-lupa"></span>
                      <input type="text" name="q" value="Поиск по сайту" class="holder" />
                      <a href="#" class="show-search-submenu"></a>
                      <div class="search-submenu">
                        <div class="row">
                          <label class="ss-label">Категория</label>
                          <div class="ss-select">
                            <select class="selectbox" style="width: 98px;">
                              <option value="1">Категория 1</option>
                              <option value="2">Категория 2</option>
                            </select>
                          </div>
                          <div class="clear"></div>
                        </div>
                        
                        <div class="row">
                          <label class="ss-label">Каталог</label>
                          <div class="ss-select">
                            <select class="selectbox" style="width: 98px;">
                              <option value="1">Каталог 1</option>
                              <option value="2">Каталог 2</option>
                            </select>
                          </div>
                          <div class="clear"></div>
                        </div>
                      </div>
                  </div>
                  <div class="but">
                      <input type="submit" value="НАЙТИ" />
                  </div>
                  <div class="clear"></div>
              </div>
          </div>
        <% end %>
          
          <div class="navigation">
            <div class="top">
              <ul>
                <% if user_signed_in? %>
                  <li class="top-nav"><a href="/">Главная</a></li>
                  <% if current_user.account %>
                    <li class="top-nav"><a href="/company_panel">Админ панель</a></li>
                    <li class="top-nav"><a href="/help">Справка</a></li>
                  <% else %>
                    <li class="top-nav"><a href="/cabinet">Личная страница</a></li>
                    <li class="top-nav"><a href="/cabinet/messages">Мои сообщения</a></li>
                  <% end %>
                  <li class="top-nav"><%= link_to "Выход", destroy_user_session_path, :method => :delete %></li>
                <% else %>
                  <li class="top-nav"><a href="#" class="view-login">Войти</a></li>
                  <li class="top-nav"><a href="#" class="view-registration">Зарегистрироваться</a></li>
                <% end %>
              </ul>
                 <ul class="icons">
                      <li><a href="/"><img src="/miniSite/images/icon-home.png" /></a></li>
                      <li><a href="javascript:void(0)" class="<%= user_signed_in? ? 'view-popup' : 'view-login' %>" data-type="send-message" data-title="Служба поддержки Наобзоре.РФ" data-to_id="<%= User.support.try(:id) %>"><img src="/miniSite/images/icon-mail.png" /></a></li>
                      <li><a href="#"><img src="/miniSite/images/icon-map.png" /></a></li>
                  </ul>
              </div>
              <!--Нижняя навигация-->
              <div class="bottom">
                  <ul>
                      <li><a href="<%= goods_path %>">Товары</a></li>
                      <li><a href="<%= services_path %>">Услуги</a></li>
                      <li><a href="<%= jobs_path %>">Вакансии</a></li>
                      <li><a href="<%= campaigns_path %>">Акции</a></li>
                      <li><a href="#" id="viewMenuItems"><img src="/miniSite/images/icon-view.png" alt="" /></a>
                          <ul class="more hidden" id="hiddenMenuItems">
                              <li><a href="<%= news_path %>">Новости</a></li>
                              <li><a href="#">Отзывы</a></li>
                              <li><a href="#">Объявления</a></li>
                          </ul>
                      </li>
                  </ul>
                  <div class="clear"></div> 
              </div>
          </div>
      </div>
  </header>
  <footer>
      <div class="active">
        
        <!-- Выподающий блок регистрации -->
          <div id="registration">
              <div class="pop-form">

                <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
                  <div class="pop-table">
                    <div><!--%= devise_error_messages! %--></div>
                      <div class="pop-table-row">
                        <%= raw Settings.find_by_key(:registration_advantages).value %>
                      </div>
                      <div class="pop-table-row">
                          <div class="pop-table-coll">Фамилия</div>
                          <div class="pop-table-colr"><%= f.text_field :f_name, :size => 20 %></div>
                      </div>
                      <div class="pop-table-row">
                          <div class="pop-table-coll">Имя</div>
                          <div class="pop-table-colr"><%= f.text_field :l_name, :size => 20 %></div>
                      </div>
                      <div class="pop-table-row">
                          <div class="pop-table-coll">Отчество</div>
                          <div class="pop-table-colr"><%= f.text_field :m_name, :size => 20 %></div>
                      </div>
                      <div class="pop-table-row">
                          <div class="pop-table-coll">E - mail</div>
                          <div class="pop-table-colr"><%= f.email_field :email, :size => 20 %></div>
                      </div>
                      <div class="pop-table-row">
                          <div class="pop-table-coll">Пароль</div>
                          <div class="pop-table-colr"><%= f.password_field :password, :size => 20 %></div>
                      </div>
                      <div class="pop-table-row">
                          <div class="pop-table-coll">Повтор пароля</div>
                          <div class="pop-table-colr"><%= f.password_field :password_confirmation, :size => 20  %></div>
                      </div>
                      <div class="pop-table-row">
                          <div class="pop-table-coll-captcha">
                              <img src="/assets/temp/captha.png" alt="" />
                              <p><a href="#" class="pop-link">Новое изображение</a></p>
                          </div>
                          <div class="pop-table-colr-captcha">
                              <p>Что Вы видите?</p><input type="text" name="" size="11" />
                          </div>
                      </div>
                      <div class="pop-table-row">
                          <div class="pop-table-col-full">
                              <%= check_box_tag "user[lic]" %> Я принимаю условия <a href="#"  class="pop-link">пользовательского соглашения</a>
                          </div>
                      </div>
                  </div>

              </div>
              <div class="pop-form-send">
                  <%= f.submit "Зарегистрироваться" %>
              </div>
          <% end %>
              
              <div class="pop-form-social">
                  Вход без регистрации 
                  <a href="#"><img src="/assets/social/facebook.png" /></a>
                  <a href="#"><img src="/assets/social/vk.png" /></a>
                  <a href="#"><img src="/assets/social/twitter.png" /></a>
              </div>
          </div>
          <!-- end | Выподающий блок регистрации -->
        
        <!-- Всплывающий блок Входа -->
          <div id="login">
          <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
              <div id="login_form">
                  <div class="pop-form-login">
                      <div class="pop-form-login-table">
                          <div class="pop-form-login-row">
                              <div class="pop-form-login-coll">E-mail</div>
                              <div class="pop-form-login-colr"><%= f.email_field :email, :size => 18 %></div>
                          </div>
                          <div class="pop-form-login-row">
                              <div class="pop-form-login-coll">Пароль</div>
                              <div class="pop-form-login-colr"><%= f.password_field :password, :size => 18 %></div>
                          </div>
                      </div>
                  </div>
                  <div class="pop-form-button">
                      <div class="pop-form-button-left"><a href="#" id="view_rec_pass">Забыли пароль?</a></div>
                      <div class="pop-form-button-right"><%= f.submit "Вход" %></div>
                  </div>
              </div>
              <div id="login_social">
                  Войти с помощью... 
                  <a href="#"><img src="/assets/social/facebook.png" /></a>
                  <a href="#"><img src="/assets/social/vk.png" /></a>
                  <a href="#"><img src="/assets/social/twitter.png" /></a>
              </div>
          <% end %>
          </div>
          <!-- end | Всплывающий блок Входа -->
          
        <span class="footer-menu">
          <% if user_signed_in? %>
            <a href="/">Главная</a> |
            <% if current_user.account %>
              <a href="/company_panel">Админ панель</a> | 
              <a href="/help">Справка</a> | 
            <% else %>
              <a href="/cabinet">Личная страница</a> |
              <a href="/cabinet/messages">Мои сообщения</a> | 
            <% end %>
            <%= link_to "Выход", destroy_user_session_path, :method => :delete %>
          <% else %>
            <a href="#" class="view-login">Войти</a> |
            <a href="#" class="view-registration">Зарегистрироваться</a>
          <% end %>
        </span>
                  
        <a href="#" id="controlTopPanel">Свернуть</a>
      </div>
  </footer>
</div>